### ISSUE TITLE
Maintain temperature when it is reached

### ISSUE THREAD

**Issue by ZeSlammy** [pascal1404/cbpi4-alarmClock#2]
More of a request than an issue 
When the temperature is reached at the specified time, would it be possible to keep the Keetle in Auto mode with the temperature as target temperature ?
At the moment I handle that through 2 steps : alarmClock followed by a 1 hour Mash Step.

**Comment by pascal1404** [comment]
It shouldn't be a problem, but I don't understand the problem. Normally after the alarm clock step there should be the mashIn step. Why do you need the 1 hour Mash Step?

**Comment by ZeSlammy** [comment]
I tricked it with a 1 hour mash step, I don't need it. At the moment, I'm using the alarm clock to have say "72° at 6:30AM" but sometimes I'm a sleepy head and I don't get to the brewery before 6:50. So once the time is reached, I'd like the step to maintain the temp if I checked something saying "no auto Next Step" or something

**Comment by pascal1404** [comment]
If you use the mashIn step, you can hold your temperature until you are ready and push the button for the next step in the notification window.
